# Generated by Django 5.1.3 on 2024-11-09 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_ui', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Link',
        ),
    ]
